permalink: /:year:month:day/:title
url: https://xtinghost.github.io/
baseurl: /
theme: jekyll-theme-minimal
# variables
name: Your Site Name
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true