permalink: /:year/:month/:day/:title/
url: https://xtinghost.github.io/
baseurl: ""

# variables
name: Neko 404
description: Hi I am a witch, working in illustration department, sometimes I also make some manga too. I love cats and magical things. And that's it. See you around :3
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
