permalink: /:2024/:may/:25/:neko/
url: https://xtinghost.github.io
baseurl: ""

# Variables
name: Hi Welcome to My World
description: Your description here
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Theme
theme: windows-95
