permalink: /:year/:month/:day/:title/
url: https://xtinghost.github.io
baseurl: ""
theme: windows-95

name: Hi Welcome to My World
description: Your description here
google_verification: null

exclude: ["README.md", "LICENSE"]

sass:
  style: :compressed
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
